# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=13)),
            ],
        ),
    ]
