# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('api_key', models.CharField(default=b'SOME STRING', max_length=250)),
                ('user_key', models.CharField(default=b'SOME STRING', max_length=500)),
                ('store_key', models.CharField(default=b'SOME STRING', max_length=500)),
            ],
        ),
    ]
