# Generated by Django 2.1.5 on 2019-02-05 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('api_key', models.CharField(default='SOME STRING', max_length=250)),
                ('user_key', models.CharField(default='SOME STRING', max_length=500)),
                ('store_key', models.CharField(default='SOME STRING', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Storefees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_type', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefees_store', to='store.Store')),
            ],
        ),
    ]
