# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storefees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_type', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefees_store', to='store.Store')),
            ],
        ),
    ]
