# Generated by Django 2.1.5 on 2019-01-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storefees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='api_key',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_key',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AlterField(
            model_name='store',
            name='user_key',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
    ]
