# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Store_id',
            new_name='store_id',
        ),
    ]
