# Generated by Django 2.1.5 on 2019-01-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190129_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='store_id',
            new_name='store',
        ),
    ]
