# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('conn_method', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=10)),
                ('orderstatus', models.BooleanField(default=True)),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='product.Product')),
            ],
        ),
    ]
